### ISSUE TITLE
Implement universe boundaries

### ISSUE THREAD

**Issue by autodidaddict** [waxosuit/stack-trader#21]
The physics system needs to stop players from moving beyond the boundaries of the shard. The shard boundaries should be readable from the shard component. The `genesis` tool accepts universe boundaries and sets that data, so the `physics` system should read from that data (and potentially cache it) to get the universe boundaries for a given shard.

**Comment by brooksmtownsend** [comment]
This issue has been fixed as of commit: 80cc22470bff3abc41891200e4a65ada3d2bbf1a
