### ISSUE TITLE
Radar system needs transponder support

### ISSUE THREAD

**Issue by brooksmtownsend** [waxosuit/stack-trader#7]
The radar system needs to detect all entities that are both in range (have a position component) and have a `radar_transponder` component. The `radar_transponder` component will contain metadata that can differentiate discovered entities on the UI (name, icon, type, etc)

**Comment by autodidaddict** [comment]
As per our conversation @brooksmtownsend :

The transponders need to convey the following information:
* The display-friendly name of the object
* The type of object that this transponder is representing

Display names for players should be the player's login name (we don't yet have logins, but we should probably rig up `Auth0` at some point to get that). The following is a list of object types:

* Starbase
* Ship
* Asteroid

The JSON for the `radar_transponder` component then might look something like this:

```json
{
    "object_type": "[starbase|ship|asteroid]",
    "display_name": "Asteroid"
}
```

we should be able to use the CoreUI Pro icons to render a starbase, a ship, or an asteroid. If not, we can find small images suitable for the radar screen display.

**Comment by autodidaddict** [comment]
In the future, if we want to have different icons for the same object type (e.g. different type of asteroid icons), we can add that later. For now, let's try and keep the scope for radar rendering as small as possible.
